name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'  

    - name: Restore dependencies
      run: dotnet restore ./Api-CI-CD/Api-CI-CD.csproj  

    - name: Build
      run: dotnet build ./Api-CI-CD/Api-CI-CD.csproj --no-restore

    - name: Run tests
      run: dotnet test ./testApi/testApi.csproj 
