name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'
    - name: Build
      run: dotnet build ./Api-CI-CD/Api-CI-CD/Api-CI-CD.csproj
    - name: Test
      run: dotnet test ./Api-CI-CD/TestsApi/TestsApi.csproj


  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()  
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      run: echo "Deploying to production"
